spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/cadastro_hersheys
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8081